### ISSUE TITLE
hi if there’s comments on a post, have it say it like if there’s 3 comments it could say “comments (3)” or something like that otherwise I won’t know to check the comments! love you :)

### ISSUE THREAD

**Issue by zanton173** [zanton173/the-family-loop#4]
error 505 on posts page

**Comment by zanton173** [comment]
I can work on this today. Love you too :)

**Comment by zanton173** [comment]
Resolved! 1666ea1

**Comment by panton85** [comment]
lol do you want more feature requests, or do you have your work cut out for you for a little bit?

[look at my repos](https://github.com/panton85/python-emailSpammer)
